--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/libPiggyEconomy2
build-by-default: true
branches:
- master
projects:
  libPiggyEconomy2:
    path: ""
    model: virion
    type: library
...
